

name: Proyecto cicd flow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build: # El trabajo se puede llamar de cualquier forma

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4 # Este paso hace que GitHub Actions descargue/cloné tu repositorio dentro de la máquina virtual.
    - name: Set up JDK 21 # Se puede llamar de cualquier forma
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      #run: mvn -B package --file pom.xml
      run: mvn clean install # Entre otros se crea el .jar
      
    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: diegorojasfa/api-springboot-image
        tags: latest
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
